### ISSUE TITLE
Running mypy on `import pyspark.sql.functions` results in segmentation fault

### ISSUE THREAD

**Issue by kjun9** [zero323/pyspark-stubs#245]
with `pyspark-stubs==2.4.0.post6`: 
```
$ mypy -c 'import pyspark.sql.functions'
Segmentation fault: 11
```

with `pyspark-stubs==2.4.0.post5`:
```
$ mypy -c 'import pyspark.sql.functions'
Success: no issues found in 1 source file
```

I'm using python 3.7.4, `mypy==0.730` and `pyspark==2.4.3`

**Comment by zero323** [comment]
That's a result of https://github.com/zero323/pyspark-stubs/pull/225 which depends on resolution of https://github.com/zero323/pyspark-stubs/pull/225.

The resolution here is to either update MyPy (in general I test this package against MyPy's master) or to downgrade this package (you should be fine, as the only significant fix was #228).

**Comment by kjun9** [comment]
Thanks for the explanation, I'll downgrade this package for now

**Comment by zero323** [comment]
Since this problem popped out again I've created a separate 2.4 branch ([`branch-2.4-mypy-0.730`](https://github.com/zero323/pyspark-stubs/tree/branch-2.4-mypy-0.730)) that drops the problematic commit. I'll do my best to keep it in-sync main `branch-2.4`, at least until Mypy 0.740 is released.

Tags corresponding to will have `-mypy-0.730` suffix (i.e [`2.4.0.post6-mypy-0.730`](https://github.com/zero323/pyspark-stubs/releases/tag/2.4.0.post6-mypy-0.730) corresponds to [`2.4.0.post6`](https://github.com/zero323/pyspark-stubs/releases/tag/2.4.0.post6)) and are signed with C095AA7F33E6123A (https://keybase.io/zero323).


CC @chehsunliu
