### ISSUE TITLE
DataFrameReader.load parameters incorrectly expected all to be strings

### ISSUE THREAD

**Issue by mark-oppenheim-edf** [zero323/pyspark-stubs#275]
Using 2.4.0.post6

```python
spark.read.load(folders, inferSchema=True, header=False)
```

mypy reports `Expected type 'str', got 'bool' instead` for both `inferSchema` and `header`.

Looks like the issue is in `third_party/3/pyspark/sql/readwriter.pyi` Line 23 where in the definition for `load()` we have `**options: str`.  For csv suppport this needs to be `**options: Optional[Union[bool, str, int]]` but to handle the general case  it probably needs to be `**options: Any`.

**Comment by zero323** [comment]
This is actually intentional, though I am open to discussion. Please note that `options` method assumes the same.

A caveat is that Scala `DataFrame(Reader|Writer).options` takes `Map[String, String]`. So to handle `options` are passed to `options` method, which in turn invoke internal `to_str` on each item, and delegate job to `option` method.

Technically speaking the actual type bound would be something like `Optional[Union[SupportsString, SupportsRepr]]` with following `Protocols`:

```python

class SupportsString(Protocol):
    def __str__(self) -> str: ...

class SupportsRepr(Protocol):
    def __repr__(self) -> str: ...
```

This might matter where either `__repr__` or `__str__`  provide unusual representation. I admit that is edge case.

You could point out that the same options passed in unambiguous contexts, like `csv`

https://github.com/zero323/pyspark-stubs/blob/76db4a4c4ea4114f7df6ae90b43c397b158df388/third_party/3/pyspark/sql/readwriter.pyi#L61

are more lenient. That's intentional as well, as these are normally passed to `option` directly, without additional conversion.

**Comment by mark-oppenheim** [comment]
@zero323 Given that, as you say:
```python
def load(self, path=None, format=None, schema=None, **options):
        ...
        self.options(**options)
        ...

def options(self, **options):
        ....
        for k in options:
            self._jreader = self._jreader.option(k, to_str(options[k]))
```

the code clearly expect _non_ string options to be passable to `load()`.

And, despite the documentation first saying: 

> *options*  – all other string options

it then gives as an example two non-string options!

```df = spark.read.format("parquet").load('python/test_support/sql/parquet_partitioned',
        opt1=True, opt2=1, opt3='str')```

I would suggest that real usage requires non-string options, and the example backs this up, but I see why you say what you do.

**Comment by zero323** [comment]
> the code clearly expect non string options to be passable to load().

We should distinguish between what is accepted (literally everything) and what is valid (a tiny subset of the universe). The path that is used here is for convenience of developers not end users. It is brittle (depends on a detail of implementation that can be easily overridden)  and can result in all kinds of undesired outcomes. 

It also rejects inputs that would be otherwise perfectly sensible. Let's imagine a made up class

```python
class BoundedDecimal(decimal.Decimal): 
    def __init__(self, v): 
        super().__init__() 
        assert 0 <= self <= 1 
    def __str__(self): 
        return f"BoundedDecimal({super().__str__()})" 
```
It should be a valid choice for let's say `samplingRatio`, but it isn't.

That's true about almost all interfaces for Java classes, and general attitude is that JVM exception is good enough. 

In general  I am opened to discussion about using the same set of known types  with known representation (`bool`, `float`, `int`, `str`) for `option`, `options` and `load` ‒ there is definitely a good case to be made for that resolution.

I am strictly against using `Any` as it includes possibly infinite number of invalid options for no good reason. 

I realize that many choices here are more restrictive than the actual implementation ‒ it is most of the time intentional, even if goes against general Python attitude, that it is easier to ask for forgiveness.

**Comment by mark-oppenheim-edf** [comment]
OK, makes sense.  I generally don't like using `Any`, and the issue you raise with Java representations makes that stronger. Your suggestion of types with a known representation should  cover all, or at least all common, real use cases whereas only handling `str` definitely rules out common (and useful) use cases.

**Comment by zero323** [comment]
> Your suggestion of types with a known representation should cover all, or at least all common, real use cases whereas only handling str definitely rules out common (and useful) use cases.

So I guess we could:

- Define an alternative alias for `Union[bool, int, float, str]` - something like `PrimitiveType` or `OptionType`. We already have https://github.com/zero323/pyspark-stubs/blob/76db4a4c4ea4114f7df6ae90b43c397b158df388/third_party/3/pyspark/sql/_typing.pyi#L18

  that covers the same set of types, but using it directly would be confusing.
- Adjust all related signatures (`option`, `options`, `load`, `save` in reader / writer and [their structured streaming counterparts](https://github.com/zero323/pyspark-stubs/blob/76db4a4c4ea4114f7df6ae90b43c397b158df388/third_party/3/pyspark/sql/streaming.pyi#L46-L81)) when applicable.
- Provide some [test data](https://github.com/zero323/pyspark-stubs/tree/master/test-data/unit) for these. 

Is it something you'd like to work on?

**Comment by mark-oppenheim-edf** [comment]
Great.  I'll be happy to do so, but will do so via my personal account.

**Comment by zero323** [comment]
Sounds good. Let's continue this discussion under #276
