### ISSUE TITLE
How to handle java backend stubs

### ISSUE THREAD

**Issue by JeroenSchmidt** [zero323/pyspark-stubs#550]
Do you have a recommendation for how I can add stub support for java private methods?

As an example, the following is a valid line of code but mypy is unable to resolve the `._gateway` java backend private method.
```python
file_system = spark.sparkContext._gateway.jvm.org.apache.hadoop.fs.FileSystem
```

**Comment by zero323** [comment]
My personal approach would be to `type: ignore` this whole thing.  That's because there are at least two problems here:

- gateway is Py4j object so it is out of scope for Spark annotations. Without annotations on their side, best we could do is annotate it with `Any`, but it is hardly an improvement.
- Even if we had external annotations for gateway, we would still have to fallback to `Any` after we reach `jvm`. Given how it works, there is no way we can do better than `Any` on `__getattr__`.

One way or another there is not much we can tell about the correctness of the code, once we reach JVM.

**Comment by zero323** [comment]
I am gonna close it, but if you have any follow-up questions, don't hesitate to ask.
